version: '3.8'

services:
  # Nama service (bebas, misal 'web')
  web:
    # Build image dari Dockerfile di folder ini
    build: .
    # Map port 5173 di komputermu (host) ke port 5173 di container
    ports:
      - "5173:5173"
    # Ini adalah kunci untuk development:
    volumes:
      # 1. Sinkronkan folder proyek saat ini ('.') ke '/app' di container
      - .:/app
      # 2. Kecualikan node_modules agar tidak disinkronkan
      #    (Kita pakai node_modules yang sudah di-instal di dalam image)
      - /app/node_modules
    # Lingkungan ini membantu hot-reloading agar bekerja di beberapa sistem
    environment:
      - CHOKIDAR_USEPOLLING=true